// Knowledge Base - Color Palettes by Product Type
// Data converted from colors.csv

import type { ColorPalette } from "./types";
import { BM25 } from "./search";

export const colorPalettes: ColorPalette[] = [
  {
    productType: "SaaS (General)",
    primary: "#2563EB",
    secondary: "#3B82F6",
    cta: "#F97316",
    background: "#F8FAFC",
    text: "#1E293B",
    border: "#E2E8F0",
    notes: "Trust blue + orange CTA contrast",
  },
  {
    productType: "Micro SaaS",
    primary: "#6366F1",
    secondary: "#818CF8",
    cta: "#10B981",
    background: "#F5F3FF",
    text: "#1E1B4B",
    border: "#E0E7FF",
    notes: "Indigo primary + emerald CTA",
  },
  {
    productType: "E-commerce (General)",
    primary: "#059669",
    secondary: "#10B981",
    cta: "#F97316",
    background: "#ECFDF5",
    text: "#064E3B",
    border: "#A7F3D0",
    notes: "Success green + urgency orange",
  },
  {
    productType: "E-commerce Luxury",
    primary: "#1C1917",
    secondary: "#44403C",
    cta: "#CA8A04",
    background: "#FAFAF9",
    text: "#0C0A09",
    border: "#D6D3D1",
    notes: "Premium dark + gold accent",
  },
  {
    productType: "Fintech",
    primary: "#0F172A",
    secondary: "#1E293B",
    cta: "#22C55E",
    background: "#F8FAFC",
    text: "#020617",
    border: "#E2E8F0",
    notes: "Trust navy + growth green",
  },
  {
    productType: "Financial Dashboard",
    primary: "#0F172A",
    secondary: "#1E293B",
    cta: "#22C55E",
    background: "#020617",
    text: "#F8FAFC",
    border: "#334155",
    notes: "Dark bg + green positive indicators",
  },
  {
    productType: "Healthcare",
    primary: "#0891B2",
    secondary: "#22D3EE",
    cta: "#059669",
    background: "#ECFEFF",
    text: "#164E63",
    border: "#A5F3FC",
    notes: "Calm cyan + health green",
  },
  {
    productType: "EdTech",
    primary: "#4F46E5",
    secondary: "#818CF8",
    cta: "#F97316",
    background: "#EEF2FF",
    text: "#1E1B4B",
    border: "#C7D2FE",
    notes: "Playful indigo + energetic orange",
  },
  {
    productType: "Developer Tools",
    primary: "#18181B",
    secondary: "#27272A",
    cta: "#22C55E",
    background: "#09090B",
    text: "#FAFAFA",
    border: "#3F3F46",
    notes: "Dark mode default + code green",
  },
  {
    productType: "AI/ML Platform",
    primary: "#7C3AED",
    secondary: "#8B5CF6",
    cta: "#06B6D4",
    background: "#0F0F23",
    text: "#F8FAFC",
    border: "#4C1D95",
    notes: "Purple AI + cyan accents + dark bg",
  },
  {
    productType: "Crypto/Web3",
    primary: "#7C3AED",
    secondary: "#A78BFA",
    cta: "#10B981",
    background: "#0A0A0F",
    text: "#F8FAFC",
    border: "#1F1F2E",
    notes: "Dark + neon purple/green",
  },
  {
    productType: "Gaming",
    primary: "#DC2626",
    secondary: "#EF4444",
    cta: "#FACC15",
    background: "#0F0F0F",
    text: "#FAFAFA",
    border: "#262626",
    notes: "Bold red + gold CTA + dark bg",
  },
  {
    productType: "Social Platform",
    primary: "#2563EB",
    secondary: "#3B82F6",
    cta: "#F97316",
    background: "#FFFFFF",
    text: "#1E293B",
    border: "#E5E7EB",
    notes: "Social blue + engagement orange",
  },
  {
    productType: "Productivity Tool",
    primary: "#374151",
    secondary: "#6B7280",
    cta: "#2563EB",
    background: "#FFFFFF",
    text: "#111827",
    border: "#E5E7EB",
    notes: "Neutral + focus blue CTA",
  },
  {
    productType: "Marketing Agency",
    primary: "#EC4899",
    secondary: "#F472B6",
    cta: "#8B5CF6",
    background: "#FFFFFF",
    text: "#18181B",
    border: "#FCE7F3",
    notes: "Creative pink + purple accent",
  },
  {
    productType: "Restaurant/Food",
    primary: "#DC2626",
    secondary: "#F87171",
    cta: "#CA8A04",
    background: "#FEF2F2",
    text: "#450A0A",
    border: "#FECACA",
    notes: "Warm red + appetite gold",
  },
  {
    productType: "Real Estate",
    primary: "#0369A1",
    secondary: "#0EA5E9",
    cta: "#059669",
    background: "#F0F9FF",
    text: "#0C4A6E",
    border: "#BAE6FD",
    notes: "Trust blue + positive green CTA",
  },
  {
    productType: "Travel/Booking",
    primary: "#0891B2",
    secondary: "#06B6D4",
    cta: "#F97316",
    background: "#ECFEFF",
    text: "#155E75",
    border: "#A5F3FC",
    notes: "Sky/ocean blue + adventure orange",
  },
  {
    productType: "News/Media",
    primary: "#18181B",
    secondary: "#27272A",
    cta: "#DC2626",
    background: "#FFFFFF",
    text: "#09090B",
    border: "#E5E7EB",
    notes: "High contrast + breaking news red",
  },
  {
    productType: "Portfolio (Personal)",
    primary: "#18181B",
    secondary: "#3F3F46",
    cta: "#2563EB",
    background: "#FFFFFF",
    text: "#09090B",
    border: "#E5E7EB",
    notes: "Minimal neutral + accent blue",
  },
  {
    productType: "Enterprise Software",
    primary: "#1E40AF",
    secondary: "#3B82F6",
    cta: "#F97316",
    background: "#F8FAFC",
    text: "#1E3A8A",
    border: "#DBEAFE",
    notes: "Corporate blue + action orange",
  },
  {
    productType: "Legal Services",
    primary: "#1E3A5F",
    secondary: "#2563EB",
    cta: "#CA8A04",
    background: "#F8FAFC",
    text: "#0F172A",
    border: "#E2E8F0",
    notes: "Navy trust + gold accent",
  },
  {
    productType: "Nonprofit/Charity",
    primary: "#059669",
    secondary: "#10B981",
    cta: "#F97316",
    background: "#ECFDF5",
    text: "#064E3B",
    border: "#A7F3D0",
    notes: "Hope green + warm donation CTA",
  },
  {
    productType: "Event/Conference",
    primary: "#7C3AED",
    secondary: "#8B5CF6",
    cta: "#F97316",
    background: "#F5F3FF",
    text: "#1E1B4B",
    border: "#DDD6FE",
    notes: "Exciting purple + urgency orange",
  },
  {
    productType: "Fitness/Gym",
    primary: "#DC2626",
    secondary: "#EF4444",
    cta: "#22C55E",
    background: "#18181B",
    text: "#FAFAFA",
    border: "#3F3F46",
    notes: "Energy red + success green + dark",
  },
  {
    productType: "Music/Audio",
    primary: "#7C3AED",
    secondary: "#A78BFA",
    cta: "#22C55E",
    background: "#09090B",
    text: "#FAFAFA",
    border: "#27272A",
    notes: "Purple vibe + play green + dark",
  },
  {
    productType: "Video Platform",
    primary: "#DC2626",
    secondary: "#EF4444",
    cta: "#FFFFFF",
    background: "#0F0F0F",
    text: "#FAFAFA",
    border: "#262626",
    notes: "Red play + white CTA + dark",
  },
  {
    productType: "Marketplace",
    primary: "#2563EB",
    secondary: "#3B82F6",
    cta: "#F97316",
    background: "#FFFFFF",
    text: "#1E293B",
    border: "#E5E7EB",
    notes: "Trust blue + buy orange",
  },
  {
    productType: "Documentation",
    primary: "#1E293B",
    secondary: "#475569",
    cta: "#2563EB",
    background: "#FFFFFF",
    text: "#0F172A",
    border: "#E2E8F0",
    notes: "High contrast readability",
  },
  {
    productType: "Analytics Dashboard",
    primary: "#1E40AF",
    secondary: "#3B82F6",
    cta: "#F59E0B",
    background: "#F8FAFC",
    text: "#1E3A8A",
    border: "#DBEAFE",
    notes: "Blue data + amber highlights",
  },
  {
    productType: "Project Management",
    primary: "#0891B2",
    secondary: "#22D3EE",
    cta: "#8B5CF6",
    background: "#FFFFFF",
    text: "#155E75",
    border: "#E5E7EB",
    notes: "Task cyan + action purple",
  },
  {
    productType: "Customer Support",
    primary: "#059669",
    secondary: "#10B981",
    cta: "#2563EB",
    background: "#FFFFFF",
    text: "#064E3B",
    border: "#E5E7EB",
    notes: "Help green + action blue",
  },
  {
    productType: "Security Platform",
    primary: "#059669",
    secondary: "#10B981",
    cta: "#2563EB",
    background: "#F0FDF4",
    text: "#064E3B",
    border: "#BBF7D0",
    notes: "Secure green + trust blue",
  },
  {
    productType: "Design Tool",
    primary: "#374151",
    secondary: "#6B7280",
    cta: "#8B5CF6",
    background: "#1F2937",
    text: "#F9FAFB",
    border: "#4B5563",
    notes: "Neutral chrome + creative purple",
  },
  {
    productType: "CRM/Sales",
    primary: "#2563EB",
    secondary: "#3B82F6",
    cta: "#22C55E",
    background: "#FFFFFF",
    text: "#1E293B",
    border: "#E5E7EB",
    notes: "Sales blue + deal green",
  },
  {
    productType: "HR/Recruiting",
    primary: "#7C3AED",
    secondary: "#8B5CF6",
    cta: "#059669",
    background: "#FFFFFF",
    text: "#1E1B4B",
    border: "#E5E7EB",
    notes: "People purple + hire green",
  },
  {
    productType: "IoT/Hardware",
    primary: "#0891B2",
    secondary: "#06B6D4",
    cta: "#F97316",
    background: "#F8FAFC",
    text: "#155E75",
    border: "#E2E8F0",
    notes: "Technical cyan + alert orange",
  },
  {
    productType: "Email Marketing",
    primary: "#F97316",
    secondary: "#FB923C",
    cta: "#2563EB",
    background: "#FFFFFF",
    text: "#1E293B",
    border: "#FED7AA",
    notes: "Email orange + send blue",
  },
  {
    productType: "Scheduling/Calendar",
    primary: "#2563EB",
    secondary: "#3B82F6",
    cta: "#059669",
    background: "#FFFFFF",
    text: "#1E293B",
    border: "#E5E7EB",
    notes: "Calendar blue + book green",
  },
  {
    productType: "Survey/Forms",
    primary: "#8B5CF6",
    secondary: "#A78BFA",
    cta: "#059669",
    background: "#FFFFFF",
    text: "#1E1B4B",
    border: "#E5E7EB",
    notes: "Form purple + submit green",
  },
  {
    productType: "File Storage/Cloud",
    primary: "#0EA5E9",
    secondary: "#38BDF8",
    cta: "#22C55E",
    background: "#F0F9FF",
    text: "#0C4A6E",
    border: "#BAE6FD",
    notes: "Cloud blue + upload green",
  },
];

// Pre-built BM25 index for color search
let colorSearchIndex: BM25<ColorPalette> | null = null;

function getColorSearchIndex(): BM25<ColorPalette> {
  if (!colorSearchIndex) {
    colorSearchIndex = new BM25(
      colorPalettes,
      (c) => `${c.productType} ${c.notes}`
    );
  }
  return colorSearchIndex;
}

/**
 * Search color palettes by query
 */
export function searchColors(query: string, maxResults = 5): ColorPalette[] {
  return getColorSearchIndex().search(query, maxResults);
}

/**
 * Get color palette by exact product type match
 */
export function getColorsByProductType(productType: string): ColorPalette | undefined {
  const typeLower = productType.toLowerCase();
  return colorPalettes.find(
    (c) => c.productType.toLowerCase() === typeLower
  );
}

/**
 * Get all color palettes
 */
export function getAllColors(): ColorPalette[] {
  return colorPalettes;
}
