// shadcn/ui Theme Generator
// Generates a shadcn-compatible theme configuration

import type { DesignStyle } from "../styles";

export interface ShadcnTheme {
  name: string;
  cssVars: {
    light: Record<string, string>;
    dark: Record<string, string>;
  };
}

function hexToHsl(hex: string): string {
  // Remove # if present
  hex = hex.replace(/^#/, "");

  // Parse hex
  const r = parseInt(hex.slice(0, 2), 16) / 255;
  const g = parseInt(hex.slice(2, 4), 16) / 255;
  const b = parseInt(hex.slice(4, 6), 16) / 255;

  const max = Math.max(r, g, b);
  const min = Math.min(r, g, b);
  let h = 0;
  let s = 0;
  const l = (max + min) / 2;

  if (max !== min) {
    const d = max - min;
    s = l > 0.5 ? d / (2 - max - min) : d / (max + min);

    switch (max) {
      case r:
        h = ((g - b) / d + (g < b ? 6 : 0)) / 6;
        break;
      case g:
        h = ((b - r) / d + 2) / 6;
        break;
      case b:
        h = ((r - g) / d + 4) / 6;
        break;
    }
  }

  return `${Math.round(h * 360)} ${Math.round(s * 100)}% ${Math.round(l * 100)}%`;
}

export function generateShadcnTheme(style: DesignStyle): ShadcnTheme {
  const primary = hexToHsl(style.colors.primary);
  const secondary = hexToHsl(style.colors.secondary);
  const accent1 = style.colors.accent[0] ? hexToHsl(style.colors.accent[0]) : primary;

  // Base light theme
  const lightVars: Record<string, string> = {
    background: "0 0% 100%",
    foreground: "0 0% 3.9%",
    card: "0 0% 100%",
    "card-foreground": "0 0% 3.9%",
    popover: "0 0% 100%",
    "popover-foreground": "0 0% 3.9%",
    primary,
    "primary-foreground": "0 0% 100%",
    secondary,
    "secondary-foreground": "0 0% 100%",
    muted: "0 0% 96.1%",
    "muted-foreground": "0 0% 45.1%",
    accent: accent1,
    "accent-foreground": "0 0% 9%",
    destructive: "0 84.2% 60.2%",
    "destructive-foreground": "0 0% 98%",
    border: "0 0% 0%",
    input: "0 0% 0%",
    ring: "0 0% 3.9%",
    radius: "0rem", // Default to no radius for brutal style
  };

  // Dark theme
  const darkVars: Record<string, string> = {
    background: "0 0% 3.9%",
    foreground: "0 0% 98%",
    card: "0 0% 3.9%",
    "card-foreground": "0 0% 98%",
    popover: "0 0% 3.9%",
    "popover-foreground": "0 0% 98%",
    primary,
    "primary-foreground": "0 0% 9%",
    secondary,
    "secondary-foreground": "0 0% 9%",
    muted: "0 0% 14.9%",
    "muted-foreground": "0 0% 63.9%",
    accent: accent1,
    "accent-foreground": "0 0% 98%",
    destructive: "0 62.8% 30.6%",
    "destructive-foreground": "0 0% 98%",
    border: "0 0% 100%",
    input: "0 0% 100%",
    ring: "0 0% 83.1%",
    radius: "0rem",
  };

  // Style-specific adjustments
  if (style.slug === "neumorphism") {
    lightVars.background = "220 15% 94%";
    lightVars.card = "220 15% 94%";
    lightVars.border = "220 15% 85%";
    lightVars.radius = "1rem";
    darkVars.background = "220 15% 20%";
    darkVars.card = "220 15% 20%";
    darkVars.border = "220 15% 30%";
    darkVars.radius = "1rem";
  } else if (style.slug === "glassmorphism") {
    lightVars.radius = "1rem";
    darkVars.radius = "1rem";
  } else if (style.slug === "editorial") {
    lightVars.radius = "0rem";
    darkVars.radius = "0rem";
  }

  return {
    name: style.slug,
    cssVars: {
      light: lightVars,
      dark: darkVars,
    },
  };
}

export function generateShadcnThemeJSON(style: DesignStyle): string {
  const theme = generateShadcnTheme(style);
  return JSON.stringify(theme, null, 2);
}

export function generateShadcnThemeCSS(style: DesignStyle): string {
  const theme = generateShadcnTheme(style);

  const lightVars = Object.entries(theme.cssVars.light)
    .map(([key, value]) => `    --${key}: ${value};`)
    .join("\n");

  const darkVars = Object.entries(theme.cssVars.dark)
    .map(([key, value]) => `    --${key}: ${value};`)
    .join("\n");

  return `/* ${style.name} (${style.nameEn}) - shadcn/ui Theme */
/* Generated by StyleKit */

@layer base {
  :root {
${lightVars}
  }

  .dark {
${darkVars}
  }
}

@layer base {
  * {
    @apply border-border;
  }
  body {
    @apply bg-background text-foreground;
  }
}
`;
}
