// Knowledge Base - Astro Guidelines
// Data converted from stacks/astro.csv

import type { StackGuideline } from "./types";

export const astroGuidelines: StackGuideline[] = [
  {
    category: "Architecture",
    guideline: "Use Islands Architecture",
    description: "Astro's partial hydration only loads JS for interactive components",
    do: "Interactive components with client directives",
    dont: "Hydrate entire page like traditional SPA",
    codeGood: "<Counter client:load />",
    codeBad: "Everything as client component",
    severity: "High",
    docsUrl: "https://docs.astro.build/en/concepts/islands/",
  },
  {
    category: "Architecture",
    guideline: "Default to zero JS",
    description: "Components render HTML by default with no JS",
    do: "Keep most components as Astro/static",
    dont: "Add interactivity unnecessarily",
    codeGood: "<Header /> (static Astro component)",
    codeBad: "<Header client:load /> for static header",
    severity: "High",
    docsUrl: "https://docs.astro.build/en/concepts/why-astro/",
  },
  {
    category: "Components",
    guideline: "Use Astro components for static",
    description: ".astro files for static HTML components",
    do: ".astro for layout, static content",
    dont: "React/Vue for non-interactive content",
    codeGood: "Layout.astro, Header.astro, Footer.astro",
    codeBad: "Header.tsx for static header",
    severity: "High",
    docsUrl: "https://docs.astro.build/en/basics/astro-components/",
  },
  {
    category: "Components",
    guideline: "Choose right client directive",
    description: "client:load, client:idle, client:visible for hydration",
    do: "client:visible for below-fold, client:idle for non-critical",
    dont: "client:load for everything",
    codeGood: "<Comments client:visible /> <Analytics client:idle />",
    codeBad: "<Footer client:load /> for below-fold",
    severity: "Medium",
    docsUrl: "https://docs.astro.build/en/reference/directives-reference/#client-directives",
  },
  {
    category: "Routing",
    guideline: "File-based routing",
    description: "Pages in src/pages/ create routes automatically",
    do: "src/pages/about.astro for /about",
    dont: "Manual route configuration",
    codeGood: "src/pages/blog/[slug].astro",
    codeBad: "Custom router setup",
    severity: "Medium",
    docsUrl: "https://docs.astro.build/en/guides/routing/",
  },
  {
    category: "Routing",
    guideline: "Use getStaticPaths for dynamic routes",
    description: "Generate static pages for dynamic routes",
    do: "export function getStaticPaths()",
    dont: "Server-render dynamic routes unnecessarily",
    codeGood: "export async function getStaticPaths() { return posts.map(p => ({ params: { slug: p.slug } })) }",
    codeBad: "Dynamic SSR for blog posts",
    severity: "Medium",
    docsUrl: "https://docs.astro.build/en/reference/api-reference/#getstaticpaths",
  },
  {
    category: "Data",
    guideline: "Fetch in frontmatter",
    description: "Data fetching in component frontmatter",
    do: "Fetch at top of .astro file",
    dont: "Client-side data fetching for static data",
    codeGood: "---\nconst posts = await fetch('/api/posts').then(r => r.json())\n---",
    codeBad: "useEffect(() => fetch(...)) in React island",
    severity: "High",
    docsUrl: "https://docs.astro.build/en/guides/data-fetching/",
  },
  {
    category: "Data",
    guideline: "Use Content Collections",
    description: "Type-safe Markdown/MDX content",
    do: "Define collection in src/content/config.ts",
    dont: "Import Markdown manually",
    codeGood: "const posts = await getCollection('blog')",
    codeBad: "import.meta.glob('./posts/*.md')",
    severity: "High",
    docsUrl: "https://docs.astro.build/en/guides/content-collections/",
  },
  {
    category: "Styling",
    guideline: "Scoped styles by default",
    description: "<style> in .astro is scoped to component",
    do: "Use scoped styles in components",
    dont: "Global styles for component-specific styling",
    codeGood: "<style>h1 { color: red; }</style> (scoped)",
    codeBad: ":global(h1) { color: red; } for single component",
    severity: "Low",
    docsUrl: "https://docs.astro.build/en/guides/styling/#scoped-styles",
  },
  {
    category: "Performance",
    guideline: "Use Image component",
    description: "Astro Image for automatic optimization",
    do: "import { Image } from 'astro:assets'",
    dont: "Plain <img> tags",
    codeGood: "<Image src={myImage} alt='...' />",
    codeBad: "<img src='/image.jpg' />",
    severity: "High",
    docsUrl: "https://docs.astro.build/en/guides/images/",
  },
  {
    category: "ViewTransitions",
    guideline: "Use View Transitions for SPA-like nav",
    description: "Smooth page transitions with View Transitions API",
    do: "import { ViewTransitions } from 'astro:transitions'",
    dont: "Client-side router for simple transitions",
    codeGood: "<ViewTransitions /> in <head>",
    codeBad: "React Router for page transitions",
    severity: "Medium",
    docsUrl: "https://docs.astro.build/en/guides/view-transitions/",
  },
  {
    category: "SEO",
    guideline: "Use Astro SEO integration",
    description: "astro-seo for meta tags management",
    do: "@astrojs/seo or manual <head> tags",
    dont: "Forget meta tags",
    codeGood: "<SEO title='...' description='...' />",
    codeBad: "No meta tags in <head>",
    severity: "High",
    docsUrl: "https://docs.astro.build/en/guides/integrations-guide/",
  },
  {
    category: "Integrations",
    guideline: "Use official integrations",
    description: "Official integrations for frameworks, tools",
    do: "npx astro add react/vue/tailwind",
    dont: "Manual setup for common tools",
    codeGood: "npx astro add react",
    codeBad: "Manual React setup",
    severity: "Medium",
    docsUrl: "https://docs.astro.build/en/guides/integrations-guide/",
  },
  {
    category: "TypeScript",
    guideline: "Use TypeScript",
    description: "Astro has built-in TypeScript support",
    do: ".astro files with TypeScript frontmatter",
    dont: "JavaScript-only projects",
    codeGood: "---\ninterface Props { title: string }\nconst { title } = Astro.props as Props\n---",
    codeBad: "No type checking",
    severity: "Medium",
    docsUrl: "https://docs.astro.build/en/guides/typescript/",
  },
  {
    category: "Build",
    guideline: "Use adapter for deployment",
    description: "Add adapter for target platform",
    do: "@astrojs/netlify, @astrojs/vercel, etc.",
    dont: "Wrong adapter for platform",
    codeGood: "adapter: vercel() in astro.config.mjs",
    codeBad: "Static output for SSR site",
    severity: "High",
    docsUrl: "https://docs.astro.build/en/guides/deploy/",
  },
];
