// Knowledge Base - HTML/Tailwind Guidelines
// Data converted from stacks/html-tailwind.csv

import type { StackGuideline } from "./types";

export const htmlTailwindGuidelines: StackGuideline[] = [
  {
    category: "Animation",
    guideline: "Use Tailwind animate utilities",
    description: "Built-in animations are optimized and respect reduced-motion",
    do: "Use animate-pulse animate-spin animate-ping",
    dont: "Custom @keyframes for simple effects",
    codeGood: "animate-pulse",
    codeBad: "@keyframes pulse {...}",
    severity: "Medium",
    docsUrl: "https://tailwindcss.com/docs/animation",
  },
  {
    category: "Z-Index",
    guideline: "Use Tailwind z-index scale",
    description: "Consistent z-index with Tailwind utilities",
    do: "z-10, z-20, z-30, z-40, z-50",
    dont: "Arbitrary z-[9999] values",
    codeGood: "z-50 for modals, z-40 for dropdowns",
    codeBad: "z-[99999]",
    severity: "Medium",
    docsUrl: "https://tailwindcss.com/docs/z-index",
  },
  {
    category: "Layout",
    guideline: "Use Flexbox/Grid utilities",
    description: "Tailwind provides complete flex and grid utilities",
    do: "flex, grid, justify-*, items-*, gap-*",
    dont: "Custom CSS for basic layouts",
    codeGood: "flex items-center justify-between gap-4",
    codeBad: "style='display: flex; ...'",
    severity: "High",
    docsUrl: "https://tailwindcss.com/docs/flex",
  },
  {
    category: "Layout",
    guideline: "Use container with max-width",
    description: "Container class for centered, max-width content",
    do: "container mx-auto px-4",
    dont: "Manual width calculations",
    codeGood: "<div class='container mx-auto px-4'>",
    codeBad: "<div style='max-width: 1280px; margin: 0 auto;'>",
    severity: "Medium",
    docsUrl: "https://tailwindcss.com/docs/container",
  },
  {
    category: "Typography",
    guideline: "Use prose for content",
    description: "@tailwindcss/typography for article content",
    do: "prose prose-lg for long-form content",
    dont: "Style every element manually",
    codeGood: "<article class='prose prose-lg'>",
    codeBad: "Manual h1, p, ul styling",
    severity: "Medium",
    docsUrl: "https://tailwindcss.com/docs/typography-plugin",
  },
  {
    category: "Typography",
    guideline: "Use text utilities consistently",
    description: "text-*, font-*, leading-*, tracking-*",
    do: "text-lg font-semibold leading-relaxed",
    dont: "Inline font-size styles",
    codeGood: "text-xl font-bold tracking-tight",
    codeBad: "style='font-size: 20px; font-weight: 700;'",
    severity: "High",
    docsUrl: "https://tailwindcss.com/docs/font-size",
  },
  {
    category: "Colors",
    guideline: "Use semantic color names",
    description: "primary, secondary, accent, muted colors",
    do: "bg-primary text-primary-foreground",
    dont: "Hardcoded hex colors",
    codeGood: "bg-primary hover:bg-primary/90",
    codeBad: "bg-[#2563eb] hover:bg-[#1d4ed8]",
    severity: "High",
    docsUrl: "https://tailwindcss.com/docs/customizing-colors",
  },
  {
    category: "Spacing",
    guideline: "Use spacing scale",
    description: "Consistent 4px scale: 1=4px, 2=8px, 4=16px, 8=32px",
    do: "p-4, m-2, gap-6, space-y-4",
    dont: "Arbitrary pixel values",
    codeGood: "p-4 m-2 gap-6",
    codeBad: "p-[13px] m-[7px]",
    severity: "Medium",
    docsUrl: "https://tailwindcss.com/docs/customizing-spacing",
  },
  {
    category: "Forms",
    guideline: "Use @tailwindcss/forms",
    description: "Form reset plugin for consistent form styling",
    do: "Add forms plugin, use form-* classes",
    dont: "Manual form element resets",
    codeGood: "<input type='text' class='form-input rounded' />",
    codeBad: "input { border: 1px solid; padding: 8px; }",
    severity: "Medium",
    docsUrl: "https://github.com/tailwindlabs/tailwindcss-forms",
  },
  {
    category: "Responsive",
    guideline: "Mobile-first responsive",
    description: "Base styles are mobile, breakpoints add larger screen styles",
    do: "text-sm md:text-base lg:text-lg",
    dont: "Desktop-first with max-width queries",
    codeGood: "w-full md:w-1/2 lg:w-1/3",
    codeBad: "w-1/3 max-md:w-full",
    severity: "High",
    docsUrl: "https://tailwindcss.com/docs/responsive-design",
  },
  {
    category: "Responsive",
    guideline: "Use breakpoint prefixes",
    description: "sm:, md:, lg:, xl:, 2xl: for responsive design",
    do: "Breakpoint prefixes for responsive styles",
    dont: "@media queries in CSS",
    codeGood: "grid-cols-1 md:grid-cols-2 lg:grid-cols-3",
    codeBad: "@media (min-width: 768px) { grid-cols: 2 }",
    severity: "High",
    docsUrl: "https://tailwindcss.com/docs/responsive-design",
  },
  {
    category: "Buttons",
    guideline: "Consistent button styles",
    description: "Use consistent padding, border-radius, focus states",
    do: "px-4 py-2 rounded-md focus:ring-2 focus:ring-offset-2",
    dont: "Different button styles across app",
    codeGood: "px-4 py-2 bg-primary text-primary-foreground rounded-md hover:bg-primary/90 focus-visible:ring-2",
    codeBad: "Inconsistent button padding/radius",
    severity: "Medium",
    docsUrl: "https://tailwindcss.com/docs/padding",
  },
  {
    category: "Cards",
    guideline: "Use shadow and rounded utilities",
    description: "Consistent card styling with shadow-*, rounded-*",
    do: "rounded-lg shadow-md p-6",
    dont: "Custom box-shadow values",
    codeGood: "bg-card rounded-lg border shadow-sm p-6",
    codeBad: "box-shadow: 0 4px 6px rgba(0,0,0,0.1)",
    severity: "Medium",
    docsUrl: "https://tailwindcss.com/docs/box-shadow",
  },
  {
    category: "Accessibility",
    guideline: "Use sr-only for screen reader text",
    description: "sr-only hides visually but accessible to screen readers",
    do: "sr-only for icon-only buttons",
    dont: "aria-label without visible text",
    codeGood: "<button><SearchIcon /><span class='sr-only'>Search</span></button>",
    codeBad: "<button aria-label='Search'><SearchIcon /></button>",
    severity: "High",
    docsUrl: "https://tailwindcss.com/docs/screen-readers",
  },
  {
    category: "Accessibility",
    guideline: "Use focus-visible for keyboard focus",
    description: "focus-visible: shows focus only on keyboard navigation",
    do: "focus-visible:ring-2 focus-visible:ring-primary",
    dont: "focus: which shows on mouse click too",
    codeGood: "focus-visible:outline-none focus-visible:ring-2",
    codeBad: "focus:ring-2",
    severity: "Medium",
    docsUrl: "https://tailwindcss.com/docs/hover-focus-and-other-states#focus-visible",
  },
  {
    category: "Performance",
    guideline: "Use JIT mode (default in v3+)",
    description: "JIT generates styles on-demand",
    do: "Use arbitrary values when needed: w-[calc(100%-2rem)]",
    dont: "Pre-generate all possible classes",
    codeGood: "w-[calc(100%-2rem)] (JIT generates)",
    codeBad: "purge: false in production",
    severity: "High",
    docsUrl: "https://tailwindcss.com/docs/just-in-time-mode",
  },
  {
    category: "Customization",
    guideline: "Extend theme in config",
    description: "Add custom values in tailwind.config.js",
    do: "theme.extend for custom colors, spacing, etc.",
    dont: "Override entire theme sections",
    codeGood: "theme: { extend: { colors: { brand: '#...' } } }",
    codeBad: "theme: { colors: { } } // loses defaults",
    severity: "High",
    docsUrl: "https://tailwindcss.com/docs/theme",
  },
];
