// Knowledge Base - Next.js Guidelines
// Data converted from stacks/nextjs.csv

import type { StackGuideline } from "./types";

export const nextjsGuidelines: StackGuideline[] = [
  {
    category: "Routing",
    guideline: "Use App Router for new projects",
    description: "App Router is the recommended approach in Next.js 14+",
    do: "app/ directory with page.tsx",
    dont: "pages/ for new projects",
    codeGood: "app/dashboard/page.tsx",
    codeBad: "pages/dashboard.tsx",
    severity: "Medium",
    docsUrl: "https://nextjs.org/docs/app",
  },
  {
    category: "Routing",
    guideline: "Use route groups for organization",
    description: "Group routes without affecting URL structure using (folder) syntax",
    do: "app/(marketing)/about/page.tsx",
    dont: "Flat structure with many files",
    codeGood: "app/(auth)/login/page.tsx",
    codeBad: "app/auth-login/page.tsx",
    severity: "Low",
    docsUrl: "https://nextjs.org/docs/app/building-your-application/routing/route-groups",
  },
  {
    category: "Routing",
    guideline: "Use parallel routes for complex layouts",
    description: "Render multiple pages simultaneously with @folder convention",
    do: "@modal and @sidebar in same layout",
    dont: "Client-side conditional rendering for modals",
    codeGood: "app/@modal/(..)photo/[id]/page.tsx",
    codeBad: "{showModal && <Modal />}",
    severity: "Medium",
    docsUrl: "https://nextjs.org/docs/app/building-your-application/routing/parallel-routes",
  },
  {
    category: "Rendering",
    guideline: "Default to Server Components",
    description: "Components are Server Components by default in App Router",
    do: "Only add 'use client' when needed",
    dont: "'use client' on every component",
    codeGood: "// Server Component by default",
    codeBad: "'use client' // for static content",
    severity: "High",
    docsUrl: "https://nextjs.org/docs/app/building-your-application/rendering/server-components",
  },
  {
    category: "Rendering",
    guideline: "Push client boundaries down",
    description: "Keep 'use client' as low in component tree as possible",
    do: "Wrap only interactive parts with client components",
    dont: "Put 'use client' at page level",
    codeGood: "<ServerPage><ClientButton /></ServerPage>",
    codeBad: "'use client' on entire page",
    severity: "High",
    docsUrl: "https://nextjs.org/docs/app/building-your-application/rendering/composition-patterns",
  },
  {
    category: "DataFetching",
    guideline: "Fetch data in Server Components",
    description: "Use async/await directly in Server Components for data",
    do: "async function Page() { const data = await fetch(...) }",
    dont: "useEffect + fetch in components",
    codeGood: "const data = await db.query(...)",
    codeBad: "useEffect(() => { fetch(...) }, [])",
    severity: "High",
    docsUrl: "https://nextjs.org/docs/app/building-your-application/data-fetching",
  },
  {
    category: "DataFetching",
    guideline: "Use Server Actions for mutations",
    description: "Server Actions are the recommended way to handle form submissions",
    do: "async function createTodo(data) { 'use server' }",
    dont: "API route for simple mutations",
    codeGood: "<form action={createTodo}>",
    codeBad: "fetch('/api/todos', { method: 'POST' })",
    severity: "Medium",
    docsUrl: "https://nextjs.org/docs/app/building-your-application/data-fetching/server-actions-and-mutations",
  },
  {
    category: "DataFetching",
    guideline: "Request memoization",
    description: "Next.js automatically memoizes fetch requests with same URL",
    do: "Call fetch multiple times - it's deduplicated",
    dont: "Manual caching of fetch results",
    codeGood: "Multiple await fetch(same-url) are deduplicated",
    codeBad: "const cache = {}; if (!cache[url]) cache[url] = await fetch(url)",
    severity: "Medium",
    docsUrl: "https://nextjs.org/docs/app/building-your-application/caching#request-memoization",
  },
  {
    category: "Images",
    guideline: "Use next/image for optimization",
    description: "next/image provides automatic optimization, lazy loading, and sizing",
    do: "import Image from 'next/image'",
    dont: "<img> tag for images",
    codeGood: "<Image src='/photo.jpg' width={500} height={300} alt='...' />",
    codeBad: "<img src='/photo.jpg' />",
    severity: "High",
    docsUrl: "https://nextjs.org/docs/app/building-your-application/optimizing/images",
  },
  {
    category: "Images",
    guideline: "Use fill for responsive images",
    description: "Use fill prop when parent has position relative and known dimensions",
    do: "<Image fill /> with sized parent",
    dont: "Fixed width/height for responsive images",
    codeGood: "<div className='relative h-64'><Image fill style={{objectFit: 'cover'}} /></div>",
    codeBad: "<Image width={1920} height={1080} /> fixed size",
    severity: "Medium",
    docsUrl: "https://nextjs.org/docs/app/api-reference/components/image#fill",
  },
  {
    category: "Fonts",
    guideline: "Use next/font for optimization",
    description: "next/font automatically optimizes and self-hosts fonts",
    do: "import { Inter } from 'next/font/google'",
    dont: "@import or <link> for Google Fonts",
    codeGood: "const inter = Inter({ subsets: ['latin'] })",
    codeBad: "@import url('https://fonts.googleapis.com/...')",
    severity: "High",
    docsUrl: "https://nextjs.org/docs/app/building-your-application/optimizing/fonts",
  },
  {
    category: "Metadata",
    guideline: "Use Metadata API",
    description: "Export metadata object or generateMetadata function for SEO",
    do: "export const metadata = { title: '...' }",
    dont: "<Head> component or manual <title>",
    codeGood: "export const metadata: Metadata = { title: 'My Page' }",
    codeBad: "<Head><title>My Page</title></Head>",
    severity: "High",
    docsUrl: "https://nextjs.org/docs/app/building-your-application/optimizing/metadata",
  },
  {
    category: "API",
    guideline: "Use Route Handlers for APIs",
    description: "Create API endpoints with route.ts files in app directory",
    do: "app/api/users/route.ts with GET/POST exports",
    dont: "pages/api for new projects",
    codeGood: "export async function GET(request: Request) { }",
    codeBad: "export default function handler(req, res) { }",
    severity: "Medium",
    docsUrl: "https://nextjs.org/docs/app/building-your-application/routing/route-handlers",
  },
  {
    category: "Middleware",
    guideline: "Use middleware for edge logic",
    description: "Middleware runs before requests for auth, redirects, rewrites",
    do: "middleware.ts at project root",
    dont: "Check auth in every page/component",
    codeGood: "export function middleware(request) { if (!auth) return redirect }",
    codeBad: "useEffect(() => { if (!user) router.push('/login') })",
    severity: "High",
    docsUrl: "https://nextjs.org/docs/app/building-your-application/routing/middleware",
  },
  {
    category: "Performance",
    guideline: "Use loading.tsx for Suspense",
    description: "loading.tsx creates automatic Suspense boundary for route segments",
    do: "app/dashboard/loading.tsx",
    dont: "Manual Suspense boundaries everywhere",
    codeGood: "app/dashboard/loading.tsx exports skeleton",
    codeBad: "<Suspense fallback={...}> around every async component",
    severity: "Medium",
    docsUrl: "https://nextjs.org/docs/app/building-your-application/routing/loading-ui-and-streaming",
  },
  {
    category: "Performance",
    guideline: "Use generateStaticParams for static paths",
    description: "Pre-render dynamic routes at build time",
    do: "export async function generateStaticParams()",
    dont: "Generate all pages on-demand",
    codeGood: "export async function generateStaticParams() { return posts.map(p => ({ slug: p.slug })) }",
    codeBad: "Dynamic rendering for static content",
    severity: "Medium",
    docsUrl: "https://nextjs.org/docs/app/api-reference/functions/generate-static-params",
  },
  {
    category: "Link",
    guideline: "Use next/link for navigation",
    description: "next/link provides prefetching and client-side navigation",
    do: "import Link from 'next/link'",
    dont: "<a> tags for internal links",
    codeGood: "<Link href='/about'>About</Link>",
    codeBad: "<a href='/about'>About</a>",
    severity: "High",
    docsUrl: "https://nextjs.org/docs/app/api-reference/components/link",
  },
  {
    category: "Security",
    guideline: "Validate Server Actions input",
    description: "Always validate and sanitize input in Server Actions",
    do: "Use Zod or similar for validation",
    dont: "Trust client input directly",
    codeGood: "const parsed = schema.parse(formData)",
    codeBad: "await db.create({ title: formData.get('title') })",
    severity: "Critical",
    docsUrl: "https://nextjs.org/docs/app/building-your-application/data-fetching/server-actions-and-mutations#security",
  },
  {
    category: "Config",
    guideline: "Use next.config.js for configuration",
    description: "Configure Next.js behavior through next.config.js",
    do: "next.config.js with proper typing",
    dont: "Workarounds that should be config options",
    codeGood: "/** @type {import('next').NextConfig} */",
    codeBad: "Runtime hacks for build configuration",
    severity: "Medium",
    docsUrl: "https://nextjs.org/docs/app/api-reference/config/next-config-js",
  },
  {
    category: "Environment",
    guideline: "Use env variables properly",
    description: "NEXT_PUBLIC_ prefix for client-side env vars",
    do: "NEXT_PUBLIC_API_URL for client, API_SECRET for server",
    dont: "Expose secrets to client",
    codeGood: "process.env.NEXT_PUBLIC_API_URL (client-safe)",
    codeBad: "process.env.DATABASE_URL in client component",
    severity: "Critical",
    docsUrl: "https://nextjs.org/docs/app/building-your-application/configuring/environment-variables",
  },
];
