// Knowledge Base - Nuxt UI Guidelines
// Data converted from stacks/nuxt-ui.csv

import type { StackGuideline } from "./types";

export const nuxtUiGuidelines: StackGuideline[] = [
  {
    category: "Installation",
    guideline: "Install as a Nuxt module",
    description: "Nuxt UI must be installed as a Nuxt module in nuxt.config.ts for auto-imports and theming to work",
    do: "Add @nuxt/ui to modules in nuxt.config.ts",
    dont: "Import components manually from the package",
    codeGood: "// nuxt.config.ts\nexport default defineNuxtConfig({ modules: ['@nuxt/ui'] });",
    codeBad: "import { UButton } from '@nuxt/ui'; // Manual import",
    severity: "Critical",
    docsUrl: "https://ui.nuxt.com/getting-started/installation",
  },
  {
    category: "Components",
    guideline: "Use U-prefixed component names",
    description: "All Nuxt UI components use the U prefix and are auto-imported when the module is installed",
    do: "Use <UButton>, <UInput>, <UCard> etc. directly in templates",
    dont: "Create wrapper components for basic UI elements that Nuxt UI already provides",
    codeGood: "<UButton color=\"primary\" variant=\"solid\" size=\"lg\">Submit</UButton>",
    codeBad: "<button class=\"btn btn-primary btn-lg\">Submit</button>",
    severity: "High",
    docsUrl: "https://ui.nuxt.com/components/button",
  },
  {
    category: "Theming",
    guideline: "Configure theme in app.config.ts",
    description: "Customize Nuxt UI component defaults and theme through app.config.ts, not CSS overrides",
    do: "Use app.config.ts ui key to customize component defaults",
    dont: "Override styles with custom CSS classes",
    codeGood: "// app.config.ts\nexport default defineAppConfig({ ui: { button: { default: { size: 'lg', color: 'primary' } } } });",
    codeBad: ".u-button { @apply px-6 py-3 !important; } // CSS overrides",
    severity: "High",
    docsUrl: "https://ui.nuxt.com/getting-started/theming",
  },
  {
    category: "Theming",
    guideline: "Use color prop for theming",
    description: "Nuxt UI components support a color prop that integrates with the Tailwind color palette",
    do: "Use the color prop with Tailwind color names",
    dont: "Apply color classes manually",
    codeGood: "<UButton color=\"red\" variant=\"soft\">Delete</UButton>",
    codeBad: "<UButton class=\"bg-red-500 text-white\">Delete</UButton>",
    severity: "Medium",
    docsUrl: "https://ui.nuxt.com/getting-started/theming#colors",
  },
  {
    category: "Forms",
    guideline: "Use UForm with validation schema",
    description: "UForm integrates with Zod, Yup, or Joi for form validation with automatic error display",
    do: "Wrap form fields in UForm with a validation schema",
    dont: "Handle form validation manually with custom error state",
    codeGood: "<UForm :schema=\"schema\" :state=\"state\" @submit=\"onSubmit\">\n  <UFormGroup label=\"Email\" name=\"email\">\n    <UInput v-model=\"state.email\" />\n  </UFormGroup>\n</UForm>",
    codeBad: "<form @submit.prevent=\"onSubmit\">\n  <input v-model=\"email\" />\n  <span v-if=\"errors.email\">{{ errors.email }}</span>\n</form>",
    severity: "High",
    docsUrl: "https://ui.nuxt.com/components/form",
  },
  {
    category: "Forms",
    guideline: "Use UFormGroup for field layout",
    description: "UFormGroup provides consistent label, description, hint, and error message layout for form fields",
    do: "Wrap each form field in UFormGroup with a name matching the schema",
    dont: "Create custom label and error layouts for each field",
    codeGood: "<UFormGroup label=\"Username\" name=\"username\" required>\n  <UInput v-model=\"state.username\" />\n</UFormGroup>",
    codeBad: "<div><label>Username</label><UInput /><span class=\"error\">{{ error }}</span></div>",
    severity: "Medium",
    docsUrl: "https://ui.nuxt.com/components/form-group",
  },
  {
    category: "Overlays",
    guideline: "Use UModal and USlideover for overlays",
    description: "Nuxt UI provides accessible modal and slideover components with proper focus management",
    do: "Use UModal for dialogs and USlideover for side panels with v-model control",
    dont: "Build custom modal implementations",
    codeGood: "<UModal v-model=\"isOpen\">\n  <UCard>\n    <template #header>Title</template>\n    Content here\n  </UCard>\n</UModal>",
    codeBad: "<div v-if=\"isOpen\" class=\"fixed inset-0 z-50\">Custom modal</div>",
    severity: "Medium",
    docsUrl: "https://ui.nuxt.com/components/modal",
  },
  {
    category: "Navigation",
    guideline: "Use navigation components for layout",
    description: "Nuxt UI provides UHeader, UFooter, UNavigationMenu, and related components for consistent app layouts",
    do: "Use UHeader and navigation components with structured link arrays",
    dont: "Build navigation from scratch with plain HTML",
    codeGood: "<UHeader :links=\"links\">\n  <template #logo>MyApp</template>\n</UHeader>",
    codeBad: "<header><nav><a v-for=\"link in links\" :href=\"link.to\">{{ link.label }}</a></nav></header>",
    severity: "Medium",
    docsUrl: "https://ui.nuxt.com/components/header",
  },
  {
    category: "Feedback",
    guideline: "Use toast for notifications",
    description: "Nuxt UI provides a toast system via the useToast composable for user feedback",
    do: "Use useToast() to show success, error, and info notifications",
    dont: "Build custom notification systems",
    codeGood: "const toast = useToast();\ntoast.add({ title: 'Saved', description: 'Your changes have been saved.', color: 'green' });",
    codeBad: "showNotification.value = true; setTimeout(() => { showNotification.value = false; }, 3000);",
    severity: "Medium",
    docsUrl: "https://ui.nuxt.com/components/toast",
  },
  {
    category: "Icons",
    guideline: "Use Iconify icons via the icon prop",
    description: "Nuxt UI integrates with Iconify for a wide selection of icon sets via the icon prop on components",
    do: "Use the icon prop with Iconify icon names (i-heroicons-*, i-lucide-*, etc.)",
    dont: "Import SVG files or use separate icon components",
    codeGood: "<UButton icon=\"i-heroicons-plus\" label=\"Add Item\" />",
    codeBad: "<UButton><PlusIcon class=\"w-4 h-4\" /> Add Item</UButton>",
    severity: "Medium",
    docsUrl: "https://ui.nuxt.com/getting-started/theming#icons",
  },
  {
    category: "DarkMode",
    guideline: "Use built-in dark mode support",
    description: "Nuxt UI components support dark mode automatically through the @nuxtjs/color-mode module",
    do: "Use the color-mode module and let Nuxt UI handle dark variants",
    dont: "Add dark: classes manually to Nuxt UI components",
    codeGood: "const colorMode = useColorMode();\ncolorMode.preference = 'dark';",
    codeBad: "<UCard class=\"dark:bg-gray-800 dark:text-white\"> // Unnecessary overrides",
    severity: "Medium",
    docsUrl: "https://ui.nuxt.com/getting-started/theming#dark-mode",
  },
  {
    category: "Customization",
    guideline: "Use the ui prop for component-level customization",
    description: "Each Nuxt UI component accepts a ui prop to override specific style slots",
    do: "Pass a ui prop object to override specific component parts",
    dont: "Use global CSS overrides or !important",
    codeGood: "<UButton :ui=\"{ base: 'font-bold tracking-wide', rounded: 'rounded-full' }\">Custom</UButton>",
    codeBad: "<UButton class=\"!font-bold !tracking-wide !rounded-full\">Custom</UButton>",
    severity: "Medium",
    docsUrl: "https://ui.nuxt.com/getting-started/theming#component",
  },
  {
    category: "Customization",
    guideline: "Use variants for component styles",
    description: "Nuxt UI components support variant, size, and color props for consistent styling",
    do: "Use built-in variant and size props for styling",
    dont: "Apply Tailwind utility classes for sizes and variants",
    codeGood: "<UButton variant=\"outline\" size=\"xl\" color=\"neutral\">Action</UButton>",
    codeBad: "<UButton class=\"border border-gray-300 px-6 py-3 text-lg\">Action</UButton>",
    severity: "High",
    docsUrl: "https://ui.nuxt.com/components/button#variants",
  },
];
