// Knowledge Base - Nuxt.js Guidelines
// Data converted from stacks/nuxtjs.csv

import type { StackGuideline } from "./types";

export const nuxtjsGuidelines: StackGuideline[] = [
  {
    category: "Routing",
    guideline: "Use file-based routing",
    description: "Nuxt automatically generates routes from the pages/ directory structure",
    do: "Create Vue files in pages/ with proper naming conventions",
    dont: "Manually configure Vue Router",
    codeGood: "pages/users/[id].vue -> /users/:id",
    codeBad: "router.addRoute({ path: '/users/:id', component: UserPage })",
    severity: "High",
    docsUrl: "https://nuxt.com/docs/getting-started/routing",
  },
  {
    category: "Routing",
    guideline: "Use NuxtLink for navigation",
    description: "NuxtLink provides automatic prefetching and client-side navigation",
    do: "Use <NuxtLink> for internal navigation",
    dont: "Use <a> tags or router.push for simple links",
    codeGood: "<NuxtLink to=\"/about\">About</NuxtLink>",
    codeBad: "<a href=\"/about\">About</a>",
    severity: "Medium",
    docsUrl: "https://nuxt.com/docs/api/components/nuxt-link",
  },
  {
    category: "AutoImports",
    guideline: "Leverage Nuxt auto-imports",
    description: "Nuxt auto-imports composables, utilities, and components without explicit import statements",
    do: "Use auto-imported composables directly (ref, computed, useFetch, etc.)",
    dont: "Manually import Vue APIs and Nuxt composables",
    codeGood: "const count = ref(0); const route = useRoute();",
    codeBad: "import { ref } from 'vue'; import { useRoute } from '#imports';",
    severity: "Medium",
    docsUrl: "https://nuxt.com/docs/guide/concepts/auto-imports",
  },
  {
    category: "DataFetching",
    guideline: "Use useFetch for data fetching",
    description: "useFetch is the primary composable for data fetching with SSR support and automatic de-duplication",
    do: "Use useFetch for API calls that need SSR support",
    dont: "Use raw fetch or axios in setup for SSR pages",
    codeGood: "const { data, pending, error } = await useFetch('/api/users');",
    codeBad: "const data = ref(null); onMounted(async () => { data.value = await $fetch('/api/users'); });",
    severity: "High",
    docsUrl: "https://nuxt.com/docs/api/composables/use-fetch",
  },
  {
    category: "DataFetching",
    guideline: "Use useAsyncData for complex fetching",
    description: "useAsyncData provides more control for complex data fetching scenarios with custom keys and transforms",
    do: "Use useAsyncData when you need custom cache keys or data transformation",
    dont: "Chain multiple useFetch calls without useAsyncData",
    codeGood: "const { data } = await useAsyncData('user-posts', () => $fetch(`/api/users/${id}/posts`));",
    codeBad: "const { data: user } = await useFetch(...); const { data: posts } = await useFetch(`/api/users/${user.value.id}/posts`);",
    severity: "Medium",
    docsUrl: "https://nuxt.com/docs/api/composables/use-async-data",
  },
  {
    category: "ServerRoutes",
    guideline: "Use server routes for API endpoints",
    description: "Define server-side API routes in the server/api/ directory with automatic file-based routing",
    do: "Create .ts files in server/api/ with defineEventHandler",
    dont: "Use external API frameworks alongside Nuxt for simple APIs",
    codeGood: "// server/api/users.get.ts\nexport default defineEventHandler(async (event) => { return await db.users.findMany(); });",
    codeBad: "Setting up a separate Express server for API routes",
    severity: "High",
    docsUrl: "https://nuxt.com/docs/guide/directory-structure/server",
  },
  {
    category: "State",
    guideline: "Use useState for shared state",
    description: "useState is an SSR-friendly composable for shared reactive state across components",
    do: "Use useState for state that needs to be shared and SSR-safe",
    dont: "Use plain ref for shared state (not SSR-safe)",
    codeGood: "const counter = useState('counter', () => 0);",
    codeBad: "const counter = ref(0); // Not SSR-safe, not shared",
    severity: "High",
    docsUrl: "https://nuxt.com/docs/api/composables/use-state",
  },
  {
    category: "State",
    guideline: "Use Pinia for complex state management",
    description: "Pinia is the recommended state management solution for complex application state in Nuxt",
    do: "Install @pinia/nuxt module and define stores with defineStore",
    dont: "Roll custom global state management with provide/inject",
    codeGood: "export const useUserStore = defineStore('user', () => { const name = ref(''); return { name }; });",
    codeBad: "const globalState = reactive({}); app.provide('state', globalState);",
    severity: "Medium",
    docsUrl: "https://nuxt.com/docs/getting-started/state-management",
  },
  {
    category: "SEO",
    guideline: "Use useHead and useSeoMeta for SEO",
    description: "Nuxt provides composables for managing head tags and SEO meta in a type-safe way",
    do: "Use useHead and useSeoMeta composables for page metadata",
    dont: "Manually add meta tags in templates",
    codeGood: "useSeoMeta({ title: 'My Page', ogTitle: 'My Page', description: 'Page description' });",
    codeBad: "<Head><meta name=\"description\" content=\"Page description\" /></Head>",
    severity: "High",
    docsUrl: "https://nuxt.com/docs/api/composables/use-seo-meta",
  },
  {
    category: "Middleware",
    guideline: "Use route middleware for guards",
    description: "Define middleware in middleware/ directory for route protection and redirects",
    do: "Create named middleware files and apply with definePageMeta",
    dont: "Check auth in every page component setup",
    codeGood: "// middleware/auth.ts\nexport default defineNuxtRouteMiddleware((to) => { if (!isAuthenticated()) return navigateTo('/login'); });",
    codeBad: "// In every page: onMounted(() => { if (!auth.value) navigateTo('/login'); });",
    severity: "High",
    docsUrl: "https://nuxt.com/docs/guide/directory-structure/middleware",
  },
  {
    category: "Rendering",
    guideline: "Configure rendering strategy per route",
    description: "Nuxt supports SSR, SSG, ISR, and SPA modes, configurable per route via routeRules",
    do: "Use routeRules in nuxt.config.ts for per-route rendering strategies",
    dont: "Use a single rendering mode for all routes",
    codeGood: "routeRules: { '/blog/**': { isr: 3600 }, '/admin/**': { ssr: false } }",
    codeBad: "ssr: false // Disabling SSR globally for the entire app",
    severity: "Medium",
    docsUrl: "https://nuxt.com/docs/guide/concepts/rendering",
  },
  {
    category: "Environment",
    guideline: "Use runtimeConfig for environment variables",
    description: "Nuxt provides runtimeConfig for type-safe environment variable access on server and client",
    do: "Define runtimeConfig in nuxt.config.ts and access with useRuntimeConfig",
    dont: "Access process.env directly in components",
    codeGood: "// nuxt.config.ts: runtimeConfig: { apiSecret: '', public: { apiBase: '' } }\nconst config = useRuntimeConfig();",
    codeBad: "const apiKey = process.env.API_KEY; // Not available in client",
    severity: "Critical",
    docsUrl: "https://nuxt.com/docs/guide/going-further/runtime-config",
  },
  {
    category: "Performance",
    guideline: "Use lazy loading for components",
    description: "Prefix components with Lazy to load them only when they are visible or needed",
    do: "Use Lazy prefix for below-the-fold or conditionally rendered components",
    dont: "Import all components eagerly",
    codeGood: "<LazyHeavyChart v-if=\"showChart\" :data=\"chartData\" />",
    codeBad: "<HeavyChart v-if=\"showChart\" :data=\"chartData\" /> <!-- Loaded even when hidden -->",
    severity: "Medium",
    docsUrl: "https://nuxt.com/docs/guide/directory-structure/components#dynamic-imports",
  },
  {
    category: "Performance",
    guideline: "Use Nuxt Image for optimized images",
    description: "The @nuxt/image module provides automatic image optimization, lazy loading, and responsive sizing",
    do: "Install @nuxt/image and use <NuxtImg> or <NuxtPicture> components",
    dont: "Use plain <img> tags without optimization",
    codeGood: "<NuxtImg src=\"/photo.jpg\" width=\"500\" height=\"300\" loading=\"lazy\" />",
    codeBad: "<img src=\"/photo.jpg\" />",
    severity: "Medium",
    docsUrl: "https://image.nuxt.com/",
  },
];
