// Knowledge Base - shadcn/ui Guidelines
// Data converted from stacks/shadcn.csv

import type { StackGuideline } from "./types";

export const shadcnGuidelines: StackGuideline[] = [
  {
    category: "Setup",
    guideline: "Use CLI for installation",
    description: "Install components via shadcn CLI for proper setup",
    do: "npx shadcn@latest add component-name",
    dont: "Manual copy-paste from docs",
    codeGood: "npx shadcn@latest add button",
    codeBad: "Copy component code manually",
    severity: "High",
    docsUrl: "https://ui.shadcn.com/docs/cli",
  },
  {
    category: "Setup",
    guideline: "Initialize project first",
    description: "Run init command before adding components",
    do: "npx shadcn@latest init",
    dont: "Add components without initialization",
    codeGood: "npx shadcn@latest init && npx shadcn@latest add button",
    codeBad: "npx shadcn@latest add button without init",
    severity: "Critical",
    docsUrl: "https://ui.shadcn.com/docs/installation",
  },
  {
    category: "Theming",
    guideline: "Use CSS variables for theming",
    description: "shadcn uses CSS variables for consistent theming",
    do: "Modify globals.css CSS variables",
    dont: "Override with Tailwind classes directly",
    codeGood: ":root { --primary: 222.2 47.4% 11.2%; }",
    codeBad: "className='bg-blue-500' instead of bg-primary",
    severity: "High",
    docsUrl: "https://ui.shadcn.com/docs/theming",
  },
  {
    category: "Theming",
    guideline: "Use theme colors",
    description: "Use semantic color names from theme",
    do: "bg-primary, text-muted-foreground, border",
    dont: "Hardcoded colors like bg-blue-500",
    codeGood: "className='bg-primary text-primary-foreground'",
    codeBad: "className='bg-blue-600 text-white'",
    severity: "High",
    docsUrl: "https://ui.shadcn.com/docs/theming#colors",
  },
  {
    category: "Components",
    guideline: "Customize in components folder",
    description: "Components are copied to your project - customize there",
    do: "Edit components/ui/button.tsx",
    dont: "Create wrappers for simple changes",
    codeGood: "// In components/ui/button.tsx, add new variant",
    codeBad: "<Button className='my-custom-classes' /> everywhere",
    severity: "Medium",
    docsUrl: "https://ui.shadcn.com/docs/components/button",
  },
  {
    category: "Components",
    guideline: "Use variants with cva",
    description: "Add variants using class-variance-authority",
    do: "Add variants to buttonVariants in component",
    dont: "Conditional className strings",
    codeGood: "const buttonVariants = cva('...', { variants: { size: { sm: '...', lg: '...' } } })",
    codeBad: "className={size === 'sm' ? 'h-8' : 'h-12'}",
    severity: "Medium",
    docsUrl: "https://ui.shadcn.com/docs/components/button#examples",
  },
  {
    category: "Dialog",
    guideline: "Use Dialog for modals",
    description: "Dialog component provides accessible modal behavior",
    do: "Use DialogTrigger, DialogContent pattern",
    dont: "Build custom modal from scratch",
    codeGood: "<Dialog><DialogTrigger>Open</DialogTrigger><DialogContent>...</DialogContent></Dialog>",
    codeBad: "{isOpen && <div className='fixed inset-0'>...</div>}",
    severity: "High",
    docsUrl: "https://ui.shadcn.com/docs/components/dialog",
  },
  {
    category: "Sheet",
    guideline: "Use Sheet for side panels",
    description: "Sheet component for slide-out panels",
    do: "Sheet with side prop for direction",
    dont: "Custom slide-in animations",
    codeGood: "<Sheet><SheetTrigger>Open</SheetTrigger><SheetContent side='right'>...</SheetContent></Sheet>",
    codeBad: "Custom CSS transform animations",
    severity: "Medium",
    docsUrl: "https://ui.shadcn.com/docs/components/sheet",
  },
  {
    category: "Form",
    guideline: "Use Form with react-hook-form",
    description: "Form components integrate with react-hook-form",
    do: "Use Form, FormField, FormItem components",
    dont: "Manual form state management",
    codeGood: "<Form {...form}><FormField control={form.control} name='email' render={...} /></Form>",
    codeBad: "<input value={email} onChange={e => setEmail(e.target.value)} />",
    severity: "High",
    docsUrl: "https://ui.shadcn.com/docs/components/form",
  },
  {
    category: "Form",
    guideline: "Use Zod for validation",
    description: "Form validation with Zod schema",
    do: "zodResolver with form schema",
    dont: "Manual validation logic",
    codeGood: "const form = useForm({ resolver: zodResolver(formSchema) })",
    codeBad: "if (!email.includes('@')) setError('Invalid')",
    severity: "Medium",
    docsUrl: "https://ui.shadcn.com/docs/components/form#define-a-schema",
  },
  {
    category: "Select",
    guideline: "Use Select for dropdowns",
    description: "Select component provides accessible dropdown",
    do: "Select with SelectTrigger, SelectContent",
    dont: "Native select or custom dropdown",
    codeGood: "<Select><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>...</SelectContent></Select>",
    codeBad: "<select><option>...</option></select>",
    severity: "Medium",
    docsUrl: "https://ui.shadcn.com/docs/components/select",
  },
  {
    category: "Command",
    guideline: "Use Command for search/palette",
    description: "Command component for searchable lists and command palettes",
    do: "Command with CommandInput, CommandList",
    dont: "Custom search input with filtered list",
    codeGood: "<Command><CommandInput /><CommandList><CommandGroup>...</CommandGroup></CommandList></Command>",
    codeBad: "<input onChange={filter} />{filtered.map(...)}",
    severity: "Medium",
    docsUrl: "https://ui.shadcn.com/docs/components/command",
  },
  {
    category: "Table",
    guideline: "Use Table components",
    description: "Table, TableHeader, TableRow for structured tables",
    do: "Use Table component set",
    dont: "Plain HTML table without styling",
    codeGood: "<Table><TableHeader><TableRow><TableHead>...</TableHead></TableRow></TableHeader></Table>",
    codeBad: "<table><thead><tr><th>...</th></tr></thead></table>",
    severity: "Medium",
    docsUrl: "https://ui.shadcn.com/docs/components/table",
  },
  {
    category: "DataTable",
    guideline: "Use DataTable for complex tables",
    description: "TanStack Table integration for sorting, filtering, pagination",
    do: "Use DataTable pattern with useReactTable",
    dont: "Build sorting/filtering from scratch",
    codeGood: "const table = useReactTable({ data, columns, getCoreRowModel: getCoreRowModel() })",
    codeBad: "Manual array sorting and slicing",
    severity: "High",
    docsUrl: "https://ui.shadcn.com/docs/components/data-table",
  },
  {
    category: "Toast",
    guideline: "Use Sonner for toasts",
    description: "Sonner provides toast notifications",
    do: "Add Toaster component and use toast()",
    dont: "Custom toast implementation",
    codeGood: "import { toast } from 'sonner'; toast('Success!')",
    codeBad: "setToastVisible(true); setTimeout(() => setToastVisible(false), 3000)",
    severity: "Medium",
    docsUrl: "https://ui.shadcn.com/docs/components/sonner",
  },
  {
    category: "Popover",
    guideline: "Use Popover for floating content",
    description: "Popover for contextual overlays",
    do: "Popover with PopoverTrigger, PopoverContent",
    dont: "Absolute positioned divs",
    codeGood: "<Popover><PopoverTrigger>Open</PopoverTrigger><PopoverContent>...</PopoverContent></Popover>",
    codeBad: "<div style={{position: 'absolute'}}>...</div>",
    severity: "Medium",
    docsUrl: "https://ui.shadcn.com/docs/components/popover",
  },
  {
    category: "DropdownMenu",
    guideline: "Use DropdownMenu for menus",
    description: "DropdownMenu for action menus",
    do: "DropdownMenu with proper keyboard nav",
    dont: "Click-to-show div menus",
    codeGood: "<DropdownMenu><DropdownMenuTrigger>...</DropdownMenuTrigger><DropdownMenuContent>...</DropdownMenuContent></DropdownMenu>",
    codeBad: "{isOpen && <div className='absolute'>...</div>}",
    severity: "High",
    docsUrl: "https://ui.shadcn.com/docs/components/dropdown-menu",
  },
  {
    category: "Tooltip",
    guideline: "Use Tooltip for hints",
    description: "Tooltip for hover information",
    do: "TooltipProvider wrapping app, Tooltip per element",
    dont: "title attribute or custom hover",
    codeGood: "<Tooltip><TooltipTrigger>Hover</TooltipTrigger><TooltipContent>Info</TooltipContent></Tooltip>",
    codeBad: "<button title='Info'>Hover</button>",
    severity: "Low",
    docsUrl: "https://ui.shadcn.com/docs/components/tooltip",
  },
  {
    category: "Skeleton",
    guideline: "Use Skeleton for loading",
    description: "Skeleton component for loading states",
    do: "Skeleton matching content shape",
    dont: "Spinner for content loading",
    codeGood: "<Skeleton className='h-4 w-[250px]' />",
    codeBad: "<div>Loading...</div>",
    severity: "Medium",
    docsUrl: "https://ui.shadcn.com/docs/components/skeleton",
  },
  {
    category: "A11y",
    guideline: "Components are accessible by default",
    description: "shadcn components built on Radix are WCAG compliant",
    do: "Use components as designed",
    dont: "Remove ARIA attributes or keyboard handlers",
    codeGood: "Use Dialog, Select, etc. as documented",
    codeBad: "role='', aria-hidden, onKeyDown removed",
    severity: "Critical",
    docsUrl: "https://ui.shadcn.com/docs/components",
  },
];
