// Knowledge Base - Svelte Guidelines
// Data converted from stacks/svelte.csv

import type { StackGuideline } from "./types";

export const svelteGuidelines: StackGuideline[] = [
  {
    category: "Reactivity",
    guideline: "Use $: for reactive declarations",
    description: "Svelte uses the $: label to create reactive statements that re-run when their dependencies change",
    do: "Use $: for derived values and reactive side effects",
    dont: "Manually track and update derived state",
    codeGood: "$: fullName = firstName + ' ' + lastName;",
    codeBad: "let fullName; function update() { fullName = firstName + ' ' + lastName; }",
    severity: "High",
    docsUrl: "https://svelte.dev/docs/svelte-components#script-3-$-marks-a-statement-as-reactive",
  },
  {
    category: "Reactivity",
    guideline: "Trigger reactivity through assignment",
    description: "Svelte reactivity is triggered by assignments, not mutations. Array/object methods alone do not trigger updates",
    do: "Reassign after mutation: arr = [...arr, item] or arr.push(item); arr = arr",
    dont: "Mutate arrays/objects without reassignment",
    codeGood: "items = [...items, newItem];",
    codeBad: "items.push(newItem); // UI does not update",
    severity: "Critical",
    docsUrl: "https://svelte.dev/docs/svelte-components#script-2-assignments-are-reactive",
  },
  {
    category: "Props",
    guideline: "Use export let for component props",
    description: "Declare props with 'export let' to expose them to parent components",
    do: "export let with default values for optional props",
    dont: "Use stores or context for simple parent-child data passing",
    codeGood: "export let variant = 'primary'; export let size = 'md';",
    codeBad: "let { variant, size } = getContext('props');",
    severity: "High",
    docsUrl: "https://svelte.dev/docs/svelte-components#script-1-export-creates-a-component-prop",
  },
  {
    category: "Stores",
    guideline: "Use stores for shared state",
    description: "Svelte stores (writable, readable, derived) provide reactive shared state across components",
    do: "Create writable stores and subscribe with $ prefix",
    dont: "Pass state through many levels of props",
    codeGood: "const count = writable(0); // In component: $count",
    codeBad: "<Parent count={count}><Child count={count}><Deep count={count} /></Child></Parent>",
    severity: "Medium",
    docsUrl: "https://svelte.dev/docs/svelte-store",
  },
  {
    category: "Stores",
    guideline: "Use derived stores for computed values",
    description: "Derived stores automatically compute values from other stores",
    do: "Use derived() to compose store values",
    dont: "Subscribe to stores and manually update another store",
    codeGood: "const doubled = derived(count, $count => $count * 2);",
    codeBad: "count.subscribe(val => { computedStore.set(val * 2); });",
    severity: "Medium",
    docsUrl: "https://svelte.dev/docs/svelte-store#derived",
  },
  {
    category: "Lifecycle",
    guideline: "Use onMount for initialization",
    description: "onMount runs after the component is first rendered to the DOM. Use it for side effects and subscriptions",
    do: "onMount for data fetching, DOM access, subscriptions",
    dont: "Access DOM or fetch data at top level of script",
    codeGood: "onMount(async () => { const res = await fetch('/api/data'); data = await res.json(); });",
    codeBad: "const res = await fetch('/api/data'); // Runs on server in SSR context",
    severity: "High",
    docsUrl: "https://svelte.dev/docs/svelte#onmount",
  },
  {
    category: "Events",
    guideline: "Use createEventDispatcher for custom events",
    description: "Dispatch custom events from child to parent using Svelte event system",
    do: "Use dispatch() and on: directive for custom events",
    dont: "Pass callback functions as props for simple events",
    codeGood: "const dispatch = createEventDispatcher(); dispatch('submit', { value });",
    codeBad: "export let onSubmit; onSubmit({ value });",
    severity: "Medium",
    docsUrl: "https://svelte.dev/docs/svelte#createeventdispatcher",
  },
  {
    category: "Transitions",
    guideline: "Use built-in transitions",
    description: "Svelte provides built-in transitions (fade, slide, fly, scale) for enter/exit animations",
    do: "Use transition:, in:, out: directives with built-in or custom transitions",
    dont: "Manually manage CSS classes for enter/exit animations",
    codeGood: "<div transition:fade={{ duration: 300 }}>Content</div>",
    codeBad: "<div class:visible={show} style='transition: opacity 0.3s'>Content</div>",
    severity: "Medium",
    docsUrl: "https://svelte.dev/docs/svelte-transition",
  },
  {
    category: "SvelteKit",
    guideline: "Use load functions for data fetching",
    description: "SvelteKit load functions run before page render and provide data to pages via the data prop",
    do: "Export load function in +page.ts or +page.server.ts",
    dont: "Fetch data in onMount for pages",
    codeGood: "export async function load({ fetch }) { const res = await fetch('/api/items'); return { items: await res.json() }; }",
    codeBad: "onMount(async () => { items = await fetch('/api/items').then(r => r.json()); });",
    severity: "High",
    docsUrl: "https://kit.svelte.dev/docs/load",
  },
  {
    category: "SvelteKit",
    guideline: "Use file-based routing conventions",
    description: "SvelteKit uses file-based routing with +page.svelte, +layout.svelte, and +server.ts conventions",
    do: "Follow SvelteKit file naming conventions for pages, layouts, and API routes",
    dont: "Create custom routing logic",
    codeGood: "src/routes/blog/[slug]/+page.svelte",
    codeBad: "Manual route matching with if/else blocks",
    severity: "High",
    docsUrl: "https://kit.svelte.dev/docs/routing",
  },
  {
    category: "Performance",
    guideline: "Use {#key} blocks for re-rendering",
    description: "Key blocks destroy and recreate content when the key value changes, useful for resetting component state",
    do: "Wrap components in {#key} block when they need full re-creation",
    dont: "Manually reset all internal state",
    codeGood: "{#key itemId}<ItemEditor item={currentItem} />{/key}",
    codeBad: "on:change={() => { resetField1(); resetField2(); resetField3(); }}",
    severity: "Medium",
    docsUrl: "https://svelte.dev/docs/special-tags#key",
  },
  {
    category: "TypeScript",
    guideline: "Use TypeScript with lang='ts'",
    description: "Svelte has first-class TypeScript support via the lang='ts' attribute on script tags",
    do: "Add lang='ts' and type props, events, and store values",
    dont: "Use untyped component interfaces",
    codeGood: "<script lang='ts'> export let count: number = 0; </script>",
    codeBad: "<script> export let count = 0; // No type safety </script>",
    severity: "Medium",
    docsUrl: "https://svelte.dev/docs/typescript",
  },
  {
    category: "Accessibility",
    guideline: "Use Svelte a11y warnings",
    description: "Svelte compiler warns about accessibility issues at build time. Address all a11y warnings",
    do: "Fix all a11y warnings from the Svelte compiler",
    dont: "Disable or ignore accessibility warnings",
    codeGood: "<img src={src} alt={description} /> <!-- No warning -->",
    codeBad: "<img src={src} /> <!-- a11y: <img> element should have an alt attribute -->",
    severity: "High",
    docsUrl: "https://svelte.dev/docs/accessibility-warnings",
  },
  {
    category: "Accessibility",
    guideline: "Use semantic elements and ARIA attributes",
    description: "Use proper HTML semantics and ARIA roles for interactive custom components",
    do: "Use <button>, <nav>, <main> and appropriate ARIA attributes",
    dont: "Use <div> with on:click for interactive elements",
    codeGood: "<button on:click={handleClick}>Submit</button>",
    codeBad: "<div on:click={handleClick}>Submit</div> <!-- Missing role, keyboard support -->",
    severity: "High",
    docsUrl: "https://svelte.dev/docs/accessibility-warnings",
  },
];
