// Knowledge Base - SwiftUI Guidelines
// Data converted from stacks/swiftui.csv

import type { StackGuideline } from "./types";

export const swiftUIGuidelines: StackGuideline[] = [
  {
    category: "Views",
    guideline: "Keep views small and composable",
    description: "SwiftUI views are lightweight value types. Extract sub-views into separate structs for readability and reuse",
    do: "Extract complex view hierarchies into smaller view structs",
    dont: "Build entire screens in a single body computed property",
    codeGood: "struct ProfileView: View {\n  var body: some View {\n    VStack { AvatarView(user: user); UserInfoView(user: user); ActionButtons(user: user) }\n  }\n}",
    codeBad: "var body: some View { VStack { /* 200 lines of nested views */ } }",
    severity: "High",
    docsUrl: "https://developer.apple.com/documentation/swiftui/view",
  },
  {
    category: "State",
    guideline: "Use @State for simple local state",
    description: "@State is for private, value-type state owned by the view. SwiftUI manages its storage and triggers redraws",
    do: "Use @State for view-local state like toggles, text fields, and counts",
    dont: "Use @State for shared state or reference types",
    codeGood: "@State private var isExpanded = false\n@State private var searchText = \"\"",
    codeBad: "@State var viewModel = UserViewModel() // Reference type, use @StateObject",
    severity: "High",
    docsUrl: "https://developer.apple.com/documentation/swiftui/state",
  },
  {
    category: "State",
    guideline: "Use @Binding for parent-child state sharing",
    description: "@Binding creates a two-way connection to a @State property owned by a parent view",
    do: "Use @Binding in child views that need to read and write parent state",
    dont: "Use closures for every state mutation from child to parent",
    codeGood: "struct ToggleRow: View {\n  @Binding var isOn: Bool\n  var body: some View { Toggle(\"Enable\", isOn: $isOn) }\n}",
    codeBad: "struct ToggleRow: View {\n  var isOn: Bool; var onToggle: (Bool) -> Void\n  // Manual callback pattern\n}",
    severity: "High",
    docsUrl: "https://developer.apple.com/documentation/swiftui/binding",
  },
  {
    category: "State",
    guideline: "Use @Observable for shared data models",
    description: "The Observation framework (@Observable macro) provides efficient observation with automatic dependency tracking",
    do: "Use @Observable class with @State or @Environment for shared models",
    dont: "Use ObservableObject with @Published for new code (older pattern)",
    codeGood: "@Observable class UserModel {\n  var name = \"\"\n  var email = \"\"\n}\n// In view: @State private var user = UserModel()",
    codeBad: "class UserModel: ObservableObject {\n  @Published var name = \"\"\n  @Published var email = \"\"\n}",
    severity: "High",
    docsUrl: "https://developer.apple.com/documentation/observation/observable()",
  },
  {
    category: "Layout",
    guideline: "Use VStack, HStack, ZStack for layout",
    description: "SwiftUI uses declarative stack-based layout. Compose views using VStack, HStack, and ZStack",
    do: "Compose layout with stacks, spacing, and alignment parameters",
    dont: "Use offset and position for basic layouts",
    codeGood: "HStack(spacing: 12) {\n  Image(systemName: \"person\")\n  VStack(alignment: .leading) { Text(name).font(.headline); Text(email).font(.subheadline) }\n  Spacer()\n}",
    codeBad: "ZStack { Text(name).offset(x: 40, y: 0); Image(\"person\").offset(x: 0, y: 0) }",
    severity: "High",
    docsUrl: "https://developer.apple.com/documentation/swiftui/building-layouts-with-stack-views",
  },
  {
    category: "Navigation",
    guideline: "Use NavigationStack for navigation",
    description: "NavigationStack provides value-based, type-safe navigation with programmatic control",
    do: "Use NavigationStack with NavigationLink(value:) and .navigationDestination",
    dont: "Use the deprecated NavigationView or NavigationLink(destination:)",
    codeGood: "NavigationStack {\n  List(items) { item in NavigationLink(value: item) { Text(item.name) } }\n  .navigationDestination(for: Item.self) { item in DetailView(item: item) }\n}",
    codeBad: "NavigationView { NavigationLink(destination: DetailView(item: item)) { Text(item.name) } }",
    severity: "High",
    docsUrl: "https://developer.apple.com/documentation/swiftui/navigationstack",
  },
  {
    category: "Lists",
    guideline: "Use List and ForEach for collections",
    description: "List provides platform-native scrolling lists. Use ForEach with Identifiable data for dynamic content",
    do: "Use List with ForEach and Identifiable conformance",
    dont: "Use ScrollView + VStack for standard list layouts",
    codeGood: "List {\n  ForEach(items) { item in ItemRow(item: item) }\n  .onDelete(perform: deleteItems)\n}",
    codeBad: "ScrollView { VStack { ForEach(items) { item in ItemRow(item: item) } } } // Loses list features",
    severity: "Medium",
    docsUrl: "https://developer.apple.com/documentation/swiftui/list",
  },
  {
    category: "Modifiers",
    guideline: "Apply modifiers in the correct order",
    description: "SwiftUI modifier order matters. Each modifier wraps the view in a new view, so order affects the result",
    do: "Apply padding before background, and background before clipShape",
    dont: "Apply modifiers in arbitrary order",
    codeGood: "Text(\"Hello\")\n  .padding()\n  .background(Color.blue)\n  .clipShape(RoundedRectangle(cornerRadius: 8))",
    codeBad: "Text(\"Hello\")\n  .background(Color.blue) // Background only covers text, not padding\n  .padding()",
    severity: "High",
    docsUrl: "https://developer.apple.com/documentation/swiftui/configuring-views",
  },
  {
    category: "Async",
    guideline: "Use .task modifier for async work",
    description: "The .task modifier runs async work when the view appears and automatically cancels when it disappears",
    do: "Use .task for data loading and async operations tied to view lifecycle",
    dont: "Use .onAppear with Task { } for async work",
    codeGood: "List(items) { ... }\n.task { items = await fetchItems() }",
    codeBad: ".onAppear { Task { items = await fetchItems() } } // Not auto-cancelled",
    severity: "Medium",
    docsUrl: "https://developer.apple.com/documentation/swiftui/view/task(priority:_:)",
  },
  {
    category: "Animation",
    guideline: "Use withAnimation for state-driven animations",
    description: "Wrap state changes in withAnimation to animate the resulting view changes",
    do: "Use withAnimation and .animation modifier for declarative animations",
    dont: "Use timers or manual frame-by-frame animation for standard transitions",
    codeGood: "Button(\"Toggle\") {\n  withAnimation(.spring()) { isExpanded.toggle() }\n}",
    codeBad: "Timer.scheduledTimer(withTimeInterval: 0.016) { ... } // Manual animation loop",
    severity: "Medium",
    docsUrl: "https://developer.apple.com/documentation/swiftui/withanimation(_:_:)",
  },
  {
    category: "Preview",
    guideline: "Create previews for all views",
    description: "Use #Preview macro for live previews in Xcode to speed up development and catch layout issues early",
    do: "Add #Preview with representative data for each view",
    dont: "Skip previews and rely only on running the full app",
    codeGood: "#Preview {\n  ProfileView(user: .preview)\n}",
    codeBad: "// No preview - must build and run entire app to see changes",
    severity: "Medium",
    docsUrl: "https://developer.apple.com/documentation/swiftui/previews-in-xcode",
  },
  {
    category: "Accessibility",
    guideline: "Add accessibility labels and traits",
    description: "SwiftUI provides accessibility modifiers to describe UI elements for VoiceOver and other assistive technologies",
    do: "Add .accessibilityLabel, .accessibilityHint, and .accessibilityAddTraits",
    dont: "Leave custom views without accessibility information",
    codeGood: "Image(systemName: \"heart.fill\")\n  .accessibilityLabel(\"Favorite\")\n  .accessibilityAddTraits(.isButton)\n  .accessibilityHint(\"Double tap to remove from favorites\")",
    codeBad: "Image(systemName: \"heart.fill\").onTapGesture { } // No accessibility info",
    severity: "High",
    docsUrl: "https://developer.apple.com/documentation/swiftui/view-accessibility",
  },
  {
    category: "Accessibility",
    guideline: "Support Dynamic Type",
    description: "Use system font styles and scalable layouts to support Dynamic Type font size adjustments",
    do: "Use .font(.body), .font(.headline) and test with all Dynamic Type sizes",
    dont: "Use fixed font sizes that do not scale with user preferences",
    codeGood: "Text(\"Title\").font(.title)\nText(\"Body\").font(.body)",
    codeBad: "Text(\"Title\").font(.system(size: 24))\nText(\"Body\").font(.system(size: 14)) // Does not scale",
    severity: "Medium",
    docsUrl: "https://developer.apple.com/documentation/swiftui/dynamictypesize",
  },
];
