// Knowledge Base - Vue Guidelines
// Data converted from stacks/vue.csv

import type { StackGuideline } from "./types";

export const vueGuidelines: StackGuideline[] = [
  {
    category: "Composition",
    guideline: "Use Composition API for new projects",
    description: "Composition API offers better TypeScript support and logic reuse",
    do: "<script setup> for components",
    dont: "Options API for new projects",
    codeGood: "<script setup>",
    codeBad: "export default { data() }",
    severity: "Medium",
    docsUrl: "https://vuejs.org/guide/extras/composition-api-faq.html",
  },
  {
    category: "Composition",
    guideline: "Use script setup",
    description: "script setup is more concise and performant",
    do: "<script setup lang='ts'>",
    dont: "setup() function in export default",
    codeGood: "<script setup lang='ts'>const count = ref(0)</script>",
    codeBad: "export default { setup() { return { count } } }",
    severity: "High",
    docsUrl: "https://vuejs.org/api/sfc-script-setup.html",
  },
  {
    category: "Reactivity",
    guideline: "Use ref for primitives",
    description: "ref() for primitive values, reactive() for objects",
    do: "ref() for strings, numbers, booleans",
    dont: "reactive() for primitives",
    codeGood: "const count = ref(0); count.value++",
    codeBad: "const count = reactive({ value: 0 })",
    severity: "Medium",
    docsUrl: "https://vuejs.org/guide/essentials/reactivity-fundamentals.html",
  },
  {
    category: "Reactivity",
    guideline: "Use reactive for objects",
    description: "reactive() makes entire object reactive",
    do: "reactive() for complex state objects",
    dont: "Nested refs in objects",
    codeGood: "const state = reactive({ user: null, isLoading: false })",
    codeBad: "const user = ref(null); const isLoading = ref(false);",
    severity: "Medium",
    docsUrl: "https://vuejs.org/guide/essentials/reactivity-fundamentals.html#reactive",
  },
  {
    category: "Watchers",
    guideline: "Use watchEffect for auto-tracking",
    description: "watchEffect auto-tracks dependencies",
    do: "watchEffect when all accessed refs should be watched",
    dont: "Manual dependency arrays when not needed",
    codeGood: "watchEffect(() => { console.log(count.value) })",
    codeBad: "watch([dep1, dep2, dep3], () => { /*uses all*/ })",
    severity: "Low",
    docsUrl: "https://vuejs.org/guide/essentials/watchers.html#watcheffect",
  },
  {
    category: "Props",
    guideline: "Use defineProps with TypeScript",
    description: "defineProps<T>() for type-safe props",
    do: "defineProps<{ title: string }>()",
    dont: "Object syntax without types",
    codeGood: "const props = defineProps<{ title: string; count: number }>()",
    codeBad: "defineProps({ title: String, count: Number })",
    severity: "High",
    docsUrl: "https://vuejs.org/guide/typescript/composition-api.html#typing-component-props",
  },
  {
    category: "Emits",
    guideline: "Use defineEmits with TypeScript",
    description: "Type-safe event emissions",
    do: "defineEmits<{ (e: 'update', id: number): void }>()",
    dont: "Untyped emits",
    codeGood: "const emit = defineEmits<{ (e: 'change', value: string): void }>()",
    codeBad: "const emit = defineEmits(['change'])",
    severity: "High",
    docsUrl: "https://vuejs.org/guide/typescript/composition-api.html#typing-component-emits",
  },
  {
    category: "Lifecycle",
    guideline: "Use onMounted for DOM access",
    description: "onMounted runs after component is mounted",
    do: "onMounted() for DOM operations, API calls",
    dont: "Direct DOM access in setup",
    codeGood: "onMounted(() => { ref.value.focus() })",
    codeBad: "document.querySelector() in setup body",
    severity: "High",
    docsUrl: "https://vuejs.org/api/composition-api-lifecycle.html#onmounted",
  },
  {
    category: "Components",
    guideline: "Auto-import components",
    description: "Components in components/ are auto-imported",
    do: "Place components in components/ folder",
    dont: "Manual import for every component",
    codeGood: "<MyComponent /> (auto-imported)",
    codeBad: "import MyComponent from '@/components/MyComponent.vue'",
    severity: "Low",
    docsUrl: "https://vuejs.org/guide/essentials/component-basics.html",
  },
  {
    category: "Composables",
    guideline: "Extract logic to composables",
    description: "Reusable logic in composables/ folder",
    do: "useFetch, useAuth, useForm composables",
    dont: "Duplicate logic across components",
    codeGood: "const { data, error } = useFetch('/api/users')",
    codeBad: "Copy-paste fetch logic in every component",
    severity: "Medium",
    docsUrl: "https://vuejs.org/guide/reusability/composables.html",
  },
  {
    category: "Templates",
    guideline: "Use v-bind shorthand",
    description: ": is shorthand for v-bind:",
    do: ":prop instead of v-bind:prop",
    dont: "Full v-bind: syntax",
    codeGood: "<input :value='name' :disabled='isLoading' />",
    codeBad: "<input v-bind:value='name' v-bind:disabled='isLoading' />",
    severity: "Low",
    docsUrl: "https://vuejs.org/guide/essentials/template-syntax.html#shorthand",
  },
  {
    category: "Templates",
    guideline: "Use v-on shorthand",
    description: "@ is shorthand for v-on:",
    do: "@click instead of v-on:click",
    dont: "Full v-on: syntax",
    codeGood: "<button @click='handleClick'>",
    codeBad: "<button v-on:click='handleClick'>",
    severity: "Low",
    docsUrl: "https://vuejs.org/guide/essentials/event-handling.html#listening-to-events",
  },
  {
    category: "State",
    guideline: "Use Pinia for global state",
    description: "Pinia is the official state management for Vue",
    do: "defineStore for global state",
    dont: "Vuex or provide/inject for complex state",
    codeGood: "const useUserStore = defineStore('user', () => { })",
    codeBad: "new Vuex.Store({ }) or provide('state', ...)",
    severity: "High",
    docsUrl: "https://pinia.vuejs.org/",
  },
  {
    category: "Performance",
    guideline: "Use v-once for static content",
    description: "v-once renders element once, no updates",
    do: "v-once for truly static content",
    dont: "v-once on content that might update",
    codeGood: "<footer v-once>Copyright 2024</footer>",
    codeBad: "<user-info v-once :user='user' />",
    severity: "Low",
    docsUrl: "https://vuejs.org/api/built-in-directives.html#v-once",
  },
  {
    category: "Performance",
    guideline: "Use computed for derived state",
    description: "computed() for derived values, cached until deps change",
    do: "computed() for filtered/sorted lists",
    dont: "Methods for derived values",
    codeGood: "const fullName = computed(() => first.value + ' ' + last.value)",
    codeBad: "function getFullName() { return first.value + ' ' + last.value }",
    severity: "High",
    docsUrl: "https://vuejs.org/guide/essentials/computed.html",
  },
];
